import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {regions, seasons, trees, type Region, type Season} from './data/trees';
import './index.css';
const frame='mx-auto w-full max-w-[1600px] px-6 lg:px-12';
function readRoute(){ const p=new URLSearchParams(location.hash.slice(1)); return {region:regions.includes(p.get('region') as Region)?p.get('region') as Region:'亚洲' as Region,tree:p.get('tree'),season:seasons.includes(p.get('season') as Season)?p.get('season') as Season:'春' as Season}; }
function route(region:Region,tree?:string,season:Season='春'){return '#'+new URLSearchParams({region,...(tree?{tree,season}:{})}).toString();}
const scrollPositions:Partial<Record<Region,number>>={};
function Photo({src,alt,label,large=false}:{src?:string;alt:string;label?:string;large?:boolean}){
 const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);
 return <figure className="m-0 min-w-0"><div className={`${large?'aspect-[16/10]':'aspect-[4/3]'} overflow-hidden rounded-[2px] bg-raised`}>{src&&!failed?<img src={src} alt={alt} onError={()=>setFailed(true)} className="h-full w-full object-cover"/>:<div className="flex h-full min-h-36 items-center justify-center border border-line px-5 text-center text-muted"><span>{alt}<br/><span className="mt-2 inline-block text-sm">{failed?'图片暂时无法显示':'照片待补充'}</span></span></div>}</div>{label&&<figcaption className="mt-2 text-sm text-muted">{label}</figcaption>}</figure>;
}
function App(){
 const [current,setCurrent]=useState(readRoute);const tree=trees.find(t=>t.id===current.tree);
 useEffect(()=>{const update=()=>setCurrent(readRoute());window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{document.title=tree?`${tree.name} · 木丛`:'地区浏览 · 木丛';if(tree||current.tree)window.scrollTo(0,0);else requestAnimationFrame(()=>window.scrollTo(0,scrollPositions[current.region]??0));},[current.tree,current.region]);
 const open=(id:string)=>{scrollPositions[current.region]=window.scrollY;location.hash=route(current.region,id);};
 const filtered=trees.filter(t=>t.region===current.region);
 return <><a href="#content" onClick={e=>{e.preventDefault();document.getElementById('content')?.focus();}} className="sr-only focus:not-sr-only focus:block focus:p-4">跳到内容</a>
 <header className="border-b border-line"><div className={`${frame} flex min-h-20 flex-wrap items-center justify-between gap-4 py-4`}><a href={route(current.region)} className="font-serif text-3xl tracking-[0.14em]">木丛</a><nav aria-label="主要导航"><a href={route(current.region)} aria-current={!current.tree?'page':undefined} className="rounded-sm border border-line px-4 py-2 text-base text-ink hover:bg-raised">地区浏览</a></nav></div></header>
 <main id="content" tabIndex={-1} className={`${frame} pb-16 pt-7 outline-none`}>
 {current.tree&&!tree?<section className="py-24"><h1 className="font-serif text-4xl">未找到这棵树</h1><a className="mt-6 inline-block underline" href={route(current.region)}>返回地区浏览</a></section>:tree?<>
 <div className="mb-6 flex flex-wrap items-center justify-between gap-3 border-b border-line pb-4"><div className="flex flex-wrap items-center gap-3 text-muted"><a className="hover:text-ink" href={route(current.region)}>← 返回{current.region}</a><span aria-hidden="true">/</span><span>{tree.place}</span><span aria-hidden="true">/</span><span className="text-ink">{tree.name}</span></div><span className="text-sm text-muted">示例档案 · 内容待核实</span></div>
 <div className="grid items-start gap-7 lg:grid-cols-12"><section aria-label="树木照片" className="min-w-0 lg:col-span-7"><Photo src={tree.photos?.[current.season]} alt={`${tree.name} · ${current.season}季`} label={tree.photos?.[current.season]?'远景 · Stitch 提供的示例影像，未核实树种与季节':`${current.season}季照片待补充，不以其他季节图片代替`} large/>
 <div className="mt-5 grid grid-cols-3 gap-3">{['中景 · 枝干','近景 · 叶片','特写 · 树皮'].map((label,i)=><Photo key={label} src={tree.details?.[i]} alt={`${tree.name} · ${label}`} label={label}/>)}</div>{tree.details&&<p className="mt-3 text-sm text-muted">细节图为 Stitch 示例影像，非已核实标本。</p>}</section>
 <section aria-label="树木介绍与季节切换" className="min-w-0 rounded-sm bg-panel p-6 lg:col-span-5 lg:p-8"><h1 className="font-serif text-[2.75rem] leading-tight">{tree.name}</h1><p className="mt-2 break-words text-muted italic">{tree.latin??'规范学名待补充'}</p><p className="mt-6 border-b border-line pb-6 leading-8">{tree.intro??'树种辨认资料待补充。当前条目为选树示例，尚未作为正式科普资料发布。'}</p>
 <div className="mt-6"><h2 className="mb-3 text-base text-muted">季节观察</h2><div className="grid grid-cols-4 gap-2" role="group" aria-label="选择季节">{seasons.map(s=><button key={s} aria-pressed={current.season===s} onClick={()=>{history.replaceState(null,'',route(current.region,tree.id,s));setCurrent({...current,season:s});}} className={`rounded-sm border py-3 font-serif text-xl transition-colors ${current.season===s?'border-black bg-accent text-white':'border-line bg-raised text-muted hover:border-muted'}`}>{s}</button>)}</div><div className="mt-4 rounded-sm bg-raised p-4 leading-8" aria-live="polite"><h3 className="mb-1 font-medium">{current.season}季</h3><p>{tree.seasonNotes?.[current.season]??'本地区的季节观察说明待补充。需结合当地气候与实拍记录，不默认所有树种都会秋黄冬落。'}</p></div></div>
 <dl className="mt-6 text-base"><div className="flex flex-wrap justify-between gap-2 border-t border-line py-4"><dt className="text-muted">地区</dt><dd>{tree.region}</dd></div><div className="flex flex-wrap justify-between gap-2 border-t border-line py-4"><dt className="text-muted">代表地区示例</dt><dd>{tree.place}</dd></div><div className="flex flex-wrap justify-between gap-2 border-t border-line pt-4"><dt className="text-muted">资料状态</dt><dd>待核实与补充</dd></div></dl></section></div>
 <div className="mt-8 grid gap-6 xl:grid-cols-3">{[{title:'辨认特点',content:tree.features},{title:'生境与气候',content:[tree.habitat??'生长环境与气候资料待补充。']},{title:'地区文化',content:[tree.culture??'地区文化联系待补充，代表地区为示例，不意味着唯一分布区或官方国树。']}].map(section=><section key={section.title} className="rounded-sm bg-panel p-6"><h2 className="mb-5 font-serif text-2xl">{section.title}</h2><ul className="space-y-4 leading-8 text-muted">{(section.content??['叶片、树皮和整体树形等辨认特点待补充。']).map(text=><li key={text}>{text}</li>)}</ul></section>)}</div>
 </>:<>
 <div className="flex flex-wrap items-end justify-between gap-5 border-b border-line pb-6"><h1 className="font-serif text-4xl">地区浏览</h1><p className="text-muted">20 种树木示例 · 亚洲 10 种</p></div>
 <nav aria-label="选择地区" className="my-7 flex flex-wrap gap-3">{regions.map(region=><a key={region} href={route(region)} aria-current={current.region===region?'page':undefined} onClick={()=>{scrollPositions[current.region]=window.scrollY;}} className={`rounded-sm border px-5 py-3 transition-colors ${current.region===region?'border-black bg-accent text-white':'border-line text-muted hover:bg-raised'}`}>{region}<span className="ml-3 text-sm">{trees.filter(t=>t.region===region).length}</span></a>)}</nav>
 <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><h2 className="font-serif text-2xl">{current.region}</h2><p className="text-sm text-muted">选树与地区关联为示例，照片和介绍持续补充</p></div>
 <div className="grid gap-x-7 gap-y-10 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(t=><a key={t.id} href={route(current.region,t.id)} onClick={e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();open(t.id);}} className="group min-w-0"><Photo src={t.photos?.春} alt={t.name}/><div className="mt-4 flex items-start justify-between gap-4"><div><h3 className="font-serif text-2xl group-hover:underline underline-offset-4">{t.name}</h3><p className="mt-1 text-sm text-muted">{t.place}</p></div><span aria-hidden="true" className="text-2xl text-muted">→</span></div><p className="mt-3 leading-7 text-muted">{t.intro??'树种介绍待补充'}</p>{t.photos&&<p className="mt-2 text-sm text-muted">Stitch 示例影像</p>}</a>)}</div>
 </>}
 </main><footer className="border-t border-line"><div className={`${frame} flex flex-wrap items-center justify-between gap-4 py-8 text-muted`}><span className="font-serif text-xl">木丛</span><a className="break-all underline underline-offset-4 hover:text-ink" href="mailto:hi_franchao@outlook.com">hi_franchao@outlook.com</a></div></footer></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
